type: "multi"  # optional: [single,multi]   
num_dip: 3

encoder:
  dip_type: ${enhancer.type}
  num_layers: 3            # dip的个数 并不一样和 encoder的层数相关
  use_pre_decoder: True   # whether using pre-decoder to more smoothly control the channels
  base_channel: 64
  encoder_output_dim: 256

gdip:
  filters: ['bezier','defog','sharpen','identity']  # optional: [bezier kernel defog sharpen,identity]
  base_channel: ${enhancer.encoder.base_channel}
  encoder_output_dim: ${enhancer.encoder.encoder_output_dim}

  bezier:
    L: 8
    num_of_params: 12
    encoder_output_dim: ${enhancer.encoder.encoder_output_dim}
  kernel:
    kernel_size: 9          
    encoder_output_dim: ${enhancer.encoder.encoder_output_dim}
  defog:
    num_of_params: 1
    use_guided_filter: True
    value_range: [0.1,1.0]
    encoder_output_dim: ${enhancer.encoder.encoder_output_dim}
  sharpen:
    sigma: 5
    kernel_size: 25
    num_of_params: 1
    value_range: [0.0,5.0]
    encoder_output_dim: ${enhancer.encoder.encoder_output_dim}

loss:
  lam_l1: 1.
  lam_msssim: 1.
  lam_text: 1.
  lam_color: 1.
  lam_con: 1.
