# --------------------------------
# 数据集配置
dataset_name: 'cdd'
train_dir: 'datasets/CDD-11_train'
val_dir: 'datasets/CDD-11_test'
modes: ['haze','low','low_haze'] # options: haze low low_haze
input_shape: [384,384]