# --------------------------------
# 数据集配置
dataset_name: 'voc'
train_txt_path: '/home/luyanlong/Desktop/Enhancer/datasets/train.txt'
val_txt_path: '/home/luyanlong/Desktop/Enhancer/datasets/val.txt'
modes: ['dark']
input_shape: [384,384]
